'use strict';

const { classify, group } = require('./group');

function esc(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function basename(path) {
  const i = path.lastIndexOf('/');
  return i === -1 ? path : path.slice(i + 1);
}

function fileBadge(file) {
  if (file.type === 'rename') return '<span class="badge rename">renamed</span>';
  if (file.type === 'add' || file.oldPath === '/dev/null')
    return '<span class="badge add">new</span>';
  if (file.type === 'delete' || file.newPath === '/dev/null')
    return '<span class="badge del">deleted</span>';
  if (file.binary) return '<span class="badge bin">binary</span>';
  if (file.noise) return '<span class="badge noise">generated</span>';
  if (file.large) return '<span class="badge large">large</span>';
  return '';
}

function renderHunk(hunk) {
  let rows = '';
  rows += `<tr class="hunk-head"><td class="ln"></td><td class="code">${esc(hunk.content)}</td></tr>`;
  for (const c of hunk.changes) {
    let cls;
    let num;
    if (c.type === 'insert') {
      cls = 'ins';
      num = c.lineNumber;
    } else if (c.type === 'delete') {
      cls = 'del';
      num = c.lineNumber;
    } else {
      cls = 'ctx';
      num = c.newLineNumber;
    }
    const sign = c.type === 'insert' ? '+' : c.type === 'delete' ? '-' : ' ';
    rows += `<tr class="${cls}"><td class="ln">${num == null ? '' : num}</td><td class="code"><span class="sign">${sign}</span>${esc(c.content)}</td></tr>`;
  }
  return rows;
}

function renderFile(file) {
  const name = basename(file.path);
  const dir = file.dir ? file.dir + '/' : '';
  const renameInfo =
    file.type === 'rename'
      ? `<div class="rename-info">${esc(file.oldPath)} → ${esc(file.newPath)}</div>`
      : '';

  let body;
  if (file.binary) {
    body = '<div class="empty">Binary file — no textual diff.</div>';
  } else if (!file.hunks || file.hunks.length === 0) {
    body = '<div class="empty">No textual changes.</div>';
  } else {
    body =
      '<table class="diff">' + file.hunks.map(renderHunk).join('') + '</table>';
  }

  const open = file.collapsed ? '' : ' open';
  const counts = `<span class="add">+${file.additions}</span> <span class="del">−${file.deletions}</span>`;
  return `
<details class="file"${open} data-path="${esc(file.path)}">
  <summary>
    <span class="caret"></span>
    <span class="fname"><span class="dir">${esc(dir)}</span>${esc(name)}</span>
    ${fileBadge(file)}
    <span class="counts">${counts}</span>
  </summary>
  ${renameInfo}
  ${body}
</details>`;
}

function renderGroup(g) {
  const label = g.dir || '(root)';
  const counts = `<span class="add">+${g.additions}</span> <span class="del">−${g.deletions}</span>`;
  return `
<details class="group" open data-dir="${esc(label)}">
  <summary>
    <span class="caret"></span>
    <span class="gname">${esc(label)}</span>
    <span class="gmeta">${g.files.length} file${g.files.length === 1 ? '' : 's'} ${counts}</span>
  </summary>
  ${g.files.map(renderFile).join('')}
</details>`;
}

function render(rawFiles, opts = {}) {
  const files = classify(rawFiles);
  const groups = group(files);
  const totalAdd = files.reduce((s, f) => s + f.additions, 0);
  const totalDel = files.reduce((s, f) => s + f.deletions, 0);
  const title = opts.title || 'pocketdiff review';
  const generated = new Date().toISOString().replace('T', ' ').slice(0, 16) + ' UTC';

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>${esc(title)}</title>
<style>${CSS}</style>
</head>
<body class="wrap">
<header class="topbar">
  <div class="title">
    <strong>${esc(title)}</strong>
    <span class="summary">${files.length} file${files.length === 1 ? '' : 's'}
      <span class="add">+${totalAdd}</span> <span class="del">−${totalDel}</span></span>
  </div>
  <div class="controls">
    <input id="filter" type="search" placeholder="Filter by filename…" autocomplete="off" autocapitalize="off" spellcheck="false">
    <button id="wrap" type="button" class="active" aria-pressed="true" title="Toggle line wrap">Wrap</button>
    <button id="expand" type="button">Expand all</button>
    <button id="collapse" type="button">Collapse all</button>
  </div>
  <div id="nomatch" class="nomatch" hidden>No files match the filter.</div>
</header>
<main>
${groups.map(renderGroup).join('')}
</main>
<footer>Generated by pocketdiff · ${generated}</footer>
<script>${JS}</script>
</body>
</html>`;
}

const CSS = `
:root{
  --bg:#ffffff; --fg:#1f2328; --muted:#656d76; --border:#d0d7de; --panel:#f6f8fa;
  --add-bg:#e6ffec; --add-fg:#1a7f37; --del-bg:#ffebe9; --del-fg:#cf222e;
  --add-num:#2da44e22; --del-num:#cf222e22; --code:#1f2328; --accent:#0969da;
}
@media (prefers-color-scheme: dark){
  :root{
    --bg:#0d1117; --fg:#e6edf3; --muted:#8b949e; --border:#30363d; --panel:#161b22;
    --add-bg:#12261e; --add-fg:#3fb950; --del-bg:#25171c; --del-fg:#f85149;
    --add-num:#3fb95022; --del-num:#f8514922; --code:#e6edf3; --accent:#58a6ff;
  }
}
*{box-sizing:border-box}
html{-webkit-text-size-adjust:100%}
body{margin:0;background:var(--bg);color:var(--fg);
  font:14px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif}
.topbar{position:sticky;top:0;z-index:10;background:var(--bg);
  border-bottom:1px solid var(--border);padding:10px 12px;
  padding-top:max(10px,env(safe-area-inset-top))}
.title{display:flex;flex-wrap:wrap;align-items:baseline;gap:8px}
.title strong{font-size:15px}
.summary{color:var(--muted);font-size:13px}
.controls{display:flex;gap:6px;margin-top:8px;flex-wrap:wrap}
#filter{flex:1 1 160px;min-width:140px;font-size:16px;padding:8px 10px;
  border:1px solid var(--border);border-radius:8px;background:var(--panel);color:var(--fg)}
.controls button{font-size:13px;padding:8px 10px;border:1px solid var(--border);
  border-radius:8px;background:var(--panel);color:var(--fg);cursor:pointer;white-space:nowrap}
.controls button:active{background:var(--border)}
.controls button.active{background:var(--accent);color:#fff;border-color:var(--accent)}
.nomatch{color:var(--muted);padding:8px 2px;font-size:13px}
main{padding:8px}
details{border:1px solid var(--border);border-radius:10px;margin:8px 0;overflow:hidden;background:var(--bg)}
details.group{background:var(--panel)}
details.group>summary{font-weight:600}
details.group>details.file{margin:8px}
summary{list-style:none;cursor:pointer;display:flex;align-items:center;gap:8px;
  padding:10px 12px;user-select:none}
summary::-webkit-details-marker{display:none}
.caret{flex:none;width:8px;height:8px;border-right:2px solid var(--muted);
  border-bottom:2px solid var(--muted);transform:rotate(-45deg);transition:transform .15s}
details[open]>summary .caret{transform:rotate(45deg)}
.gname{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:13px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.gmeta{margin-left:auto;color:var(--muted);font-size:12px;white-space:nowrap}
.fname{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:13px;
  overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1 1 auto;min-width:0}
.fname .dir{color:var(--muted)}
.counts{margin-left:auto;white-space:nowrap;font-size:12px}
.add{color:var(--add-fg);font-weight:600}
.del{color:var(--del-fg);font-weight:600}
.badge{font-size:10px;text-transform:uppercase;letter-spacing:.04em;padding:2px 6px;
  border-radius:20px;border:1px solid var(--border);color:var(--muted);flex:none}
.badge.add{color:var(--add-fg)} .badge.del{color:var(--del-fg)}
.badge.rename,.badge.bin,.badge.noise,.badge.large{color:var(--accent)}
.rename-info{padding:6px 12px;color:var(--muted);font-family:ui-monospace,monospace;
  font-size:12px;border-top:1px solid var(--border)}
.empty{padding:12px;color:var(--muted);border-top:1px solid var(--border)}
table.diff{width:100%;border-collapse:collapse;border-top:1px solid var(--border);
  display:block;overflow-x:auto;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;
  font-size:12.5px;line-height:1.45;-webkit-overflow-scrolling:touch}
table.diff tr{display:flex}
td.ln{flex:none;width:44px;text-align:right;padding:0 8px;color:var(--muted);
  user-select:none;background:var(--panel);position:sticky;left:0}
td.code{flex:1 1 auto;padding:0 8px;white-space:pre;color:var(--code);min-width:0}
.sign{display:inline-block;width:1ch;color:var(--muted)}
tr.ins td.code{background:var(--add-bg)} tr.ins td.ln{background:var(--add-num)}
tr.ins .sign{color:var(--add-fg)}
tr.del td.code{background:var(--del-bg)} tr.del td.ln{background:var(--del-num)}
tr.del .sign{color:var(--del-fg)}
tr.hunk-head td{color:var(--accent);background:var(--panel);font-size:12px}
body.wrap table.diff{display:table;table-layout:fixed;width:100%;overflow-x:visible}
body.wrap table.diff tr{display:table-row}
body.wrap td.ln{display:table-cell;position:static;vertical-align:top}
body.wrap td.code{display:table-cell;white-space:pre-wrap;overflow-wrap:anywhere;word-break:break-word}
footer{color:var(--muted);text-align:center;font-size:12px;padding:16px;
  padding-bottom:max(16px,env(safe-area-inset-bottom))}
.hidden{display:none !important}
/* tablet / landscape: roomier code, wider gutter */
@media (min-width:768px){
  main{max-width:980px;margin:0 auto}
  table.diff{font-size:13.5px}
  td.ln{width:56px}
}
`;

const JS = `
(function(){
  var filter=document.getElementById('filter');
  var nomatch=document.getElementById('nomatch');
  var files=Array.prototype.slice.call(document.querySelectorAll('details.file'));
  var groups=Array.prototype.slice.call(document.querySelectorAll('details.group'));
  function apply(){
    var q=filter.value.trim().toLowerCase();
    var any=false;
    files.forEach(function(f){
      var match=!q||f.getAttribute('data-path').toLowerCase().indexOf(q)!==-1;
      f.classList.toggle('hidden',!match);
      if(match)any=true;
    });
    groups.forEach(function(g){
      var visible=g.querySelectorAll('details.file:not(.hidden)').length;
      g.classList.toggle('hidden',visible===0);
    });
    nomatch.hidden=any;
  }
  filter.addEventListener('input',apply);
  document.getElementById('wrap').addEventListener('click',function(){
    var on=document.body.classList.toggle('wrap');
    this.classList.toggle('active',on);
    this.setAttribute('aria-pressed',String(on));
  });
  document.getElementById('expand').addEventListener('click',function(){
    files.forEach(function(f){if(!f.classList.contains('hidden'))f.open=true;});
    groups.forEach(function(g){g.open=true;});
  });
  document.getElementById('collapse').addEventListener('click',function(){
    files.forEach(function(f){f.open=false;});
  });
})();
`;

module.exports = { render, esc };
